############## CRASHES ####################

COLUMNS_TO_DROP_CRASHES = [
    "CRASH_DATE_EST_I",
    "LANE_CNT",
    "INTERSECTION_RELATED_I",
    "NOT_RIGHT_OF_WAY_I",
    "HIT_AND_RUN_I",
    "PHOTOS_TAKEN_I",
    "STATEMENTS_TAKEN_I",
    "DOORING_I",
    "WORK_ZONE_I",
    "WORK_ZONE_TYPE",
    "WORKERS_PRESENT_I",  
    "CRASH_HOUR",
    "CRASH_DAY_OF_WEEK",
    "CRASH_MONTH",
    "LOCATION",
]

# tu nulle UNKNOWN
COLUMNS_TO_STRING_CRASHES = [
    "TRAFFIC_CONTROL_DEVICE",
    "DEVICE_CONDITION",
    "WEATHER_CONDITION",
    "LIGHTING_CONDITION",
    "FIRST_CRASH_TYPE",
    "TRAFFICWAY_TYPE",
    "ALIGNMENT",
    "ROADWAY_SURFACE_COND",
    "ROAD_DEFECT",
    "REPORT_TYPE",
    "CRASH_TYPE",
    "DAMAGE",
    "PRIM_CONTRIBUTORY_CAUSE",
    "SEC_CONTRIBUTORY_CAUSE",
    "STREET_DIRECTION",
    "STREET_NAME",
    "MOST_SEVERE_INJURY",
]

COLUMNS_TO_INT_CRASHES = [
    "POSTED_SPEED_LIMIT",
    "STREET_NO",
    "BEAT_OF_OCCURRENCE",
    "NUM_UNITS",
    "INJURIES_TOTAL",
    "INJURIES_FATAL",
    "INJURIES_INCAPACITATING",
    "INJURIES_NON_INCAPACITATING",
    "INJURIES_REPORTED_NOT_EVIDENT",
    "INJURIES_NO_INDICATION",
    "INJURIES_UNKNOWN",
]

COLUMNS_TO_FLOAT_CRASHES = [
    "LATITUDE",
    "LONGITUDE"
]

# TODO
COLUMNS_TO_DATE = [
    "CRASH_DATE",
    "DATE_POLICE_NOTIFIED",
]

############## PEOPLE ##################







############## VEHICLES #################







############## WEATHER ##################

