# Ten plik zawiera listy kolumn, które powinny być w plikach CSV, które będziemy przetwarzać."""
# Zakomentowane kolumny to te, które są zbędne lub mają zbyt wiele wartości null.


EXPECTED_CRASHES_COLUMNS = {
"CRASH_RECORD_ID",
# "CRASH_DATE_EST_I",       to same nulle
"CRASH_DATE",
"POSTED_SPEED_LIMIT",
"TRAFFIC_CONTROL_DEVICE",
"DEVICE_CONDITION",
"WEATHER_CONDITION",
"LIGHTING_CONDITION",
"FIRST_CRASH_TYPE",
"TRAFFICWAY_TYPE",
# "LANE_CNT",               to też same nulle
"ALIGNMENT",
"ROADWAY_SURFACE_COND",
"ROAD_DEFECT",
"REPORT_TYPE",
"CRASH_TYPE",
# "INTERSECTION_RELATED_I", same
# "NOT_RIGHT_OF_WAY_I",
# "HIT_AND_RUN_I",
"DAMAGE",
"DATE_POLICE_NOTIFIED",
"PRIM_CONTRIBUTORY_CAUSE",
"SEC_CONTRIBUTORY_CAUSE",
"STREET_NO",
"STREET_DIRECTION",
"STREET_NAME",
"BEAT_OF_OCCURRENCE",
# "PHOTOS_TAKEN_I",
# "STATEMENTS_TAKEN_I",
# "DOORING_I",
# "WORK_ZONE_I",
# "WORK_ZONE_TYPE",
# "WORKERS_PRESENT_I",     w tych to samo
"NUM_UNITS",
"MOST_SEVERE_INJURY",
"INJURIES_TOTAL",
"INJURIES_FATAL",
"INJURIES_INCAPACITATING",
"INJURIES_NON_INCAPACITATING",
"INJURIES_REPORTED_NOT_EVIDENT",
"INJURIES_NO_INDICATION",
"INJURIES_UNKNOWN",
# "CRASH_HOUR",
# "CRASH_DAY_OF_WEEK",
# "CRASH_MONTH",
"LATITUDE",
"LONGITUDE",
# "LOCATION",                     # to niepotrzebne bo to jest punkt (latitude, longitude)
}

EXPECTED_PEOPLE_COLUMNS = {
"PERSON_ID",
"PERSON_TYPE",
"CRASH_RECORD_ID",
"VEHICLE_ID",
# "CRASH_DATE",          # nie potrzebujemy chyba bo to mamy w crashes a się łączą po CRASH_RECORD_ID
# "SEAT_NO",             # nulli dużo
# "CITY",                # nulli z 27% ale nie potrzebujemy chyba tego (ew można dać)
# "STATE",               # to co wyżej
# "ZIPCODE",             # też to co wyżej
"SEX",              
"AGE",                   # tutaj 29% nulli, nwm może dać im 0? xd
# "DRIVERS_LICENSE_STATE",
# "DRIVERS_LICENSE_CLASS",
"SAFETY_EQUIPMENT",
"AIRBAG_DEPLOYED",
"EJECTION",
"INJURY_CLASSIFICATION",
# "HOSPITAL",            # nulli dużo
# "EMS_AGENCY",
# "EMS_RUN_NO",
"DRIVER_ACTION",
"DRIVER_VISION",
"PHYSICAL_CONDITION",
# "PEDPEDAL_ACTION",
# "PEDPEDAL_VISIBILITY",
# "PEDPEDAL_LOCATION",
"BAC_RESULT",
"BAC_RESULT VALUE",
# "CELL_PHONE_USE",
}


EXPECTED_VEHICLES_COLUMNS = {
"CRASH_UNIT_ID",
"CRASH_RECORD_ID",
"CRASH_DATE",
"UNIT_NO",
"UNIT_TYPE",
# "NUM_PASSENGERS",     # nulle
"VEHICLE_ID",
# "CMRC_VEH_I",         # nulle
"MAKE",
"MODEL",
# "LIC_PLATE_STATE",    # niepotrzebne
"VEHICLE_YEAR",
"VEHICLE_DEFECT",
# "VEHICLE_TYPE",       # useless
"VEHICLE_USE",
"TRAVEL_DIRECTION",
"MANEUVER",
# "TOWED_I",            # nulle
# "FIRE_I",             # nulle
"OCCUPANT_CNT",
# "EXCEED_SPEED_LIMIT_I",
# "TOWED_BY",
# "TOWED_TO",
# "AREA_00_I",
# "AREA_01_I",
# "AREA_02_I",
# "AREA_03_I",
# "AREA_04_I",
# "AREA_05_I",
# "AREA_06_I",
# "AREA_07_I",
# "AREA_08_I",
# "AREA_09_I",
# "AREA_10_I",
# "AREA_11_I",
# "AREA_12_I",
# "AREA_99_I",
"FIRST_CONTACT_POINT",
# # "CMV_ID",
# "USDOT_NO",
# "CCMC_NO",
# "ILCC_NO",
# "COMMERCIAL_SRC",
# "GVWR",
# "CARRIER_NAME",
# "CARRIER_STATE",
# "CARRIER_CITY",
# "HAZMAT_PLACARDS_I",
# "HAZMAT_NAME",
# "UN_NO",
# "HAZMAT_PRESENT_I",
# "HAZMAT_REPORT_I",
# "HAZMAT_REPORT_NO",
# "MCS_REPORT_I",
# "MCS_REPORT_NO",
# "HAZMAT_VIO_CAUSE_CRASH_I",
# "MCS_VIO_CAUSE_CRASH_I",
# "IDOT_PERMIT_NO",
# "WIDE_LOAD_I",
# "TRAILER1_WIDTH",
# "TRAILER2_WIDTH",
# "TRAILER1_LENGTH",
# "TRAILER2_LENGTH",
# "TOTAL_VEHICLE_LENGTH",
# "AXLE_CNT",
# "VEHICLE_CONFIG",
# "CARGO_BODY_TYPE",
# "LOAD_TYPE",
# "HAZMAT_OUT_OF_SERVICE_I",
# "MCS_OUT_OF_SERVICE_I",
# "HAZMAT_CLASS",
}

EXPECTED_WEATHER_COLUMNS = {
# "name",
"datetime",
"temp",
"feelslike",
"dew",
"humidity",
"precip",
# "precipprob",     # to w sumie usuńmy bo są albo 0 albo 100
"preciptype",
"snow",
"snowdepth",
"windgust",
"windspeed",
"winddir",
"sealevelpressure",
"cloudcover",
"visibility",
"solarradiation",
"solarenergy",
"uvindex",
# "severerisk",
"conditions",
"icon",
"stations",
}